### PR TITLE
Adds Point#negate and Range#negate

### PR DESCRIPTION
**Pull request by secrettriangle**

### CODE REVIEW

**Comment by kevinsawicki** [comment]
Would you mind adding some tests for this new method?

**Comment by secrettriangle** [comment]
Sure! Should I make a new `spec/point-spec.coffee` file, or include it in an existing file?

**Comment by kevinsawicki** [comment]
If you think `Range.negate` would be helpful as well, then I'd say add it and just test it for both points and ranges through `range-spec.coffee`.

But if you don't think this method will also be useful for `Range`s then a new spec file (`point-spec.coffee`) is good.

**Comment by secrettriangle** [comment]
I've updated the PR:

* Added Range#negate
* Created point-spec.coffee
* Testing Range#negate in range-spec.coffee

**Comment by kevinsawicki** [comment]
Thanks for adding the specs!

**Comment by kevinsawicki** [comment]
Publishes in 4.1.0

**Pull request merged**
