### PR TITLE
Add note about creating Points with one argument

### PR DESCRIPTION
**Pull request by mnquintana**
Just discovered that you can create a Point from one argument or a 1-element Array, which is currently undocumented.

/cc @atom/feedback

### CODE REVIEW

**Comment by benogle** [comment]
cc @nathansobo

**Comment by nathansobo** [comment]
This is an accidental feature that some have used in some places. Question is whether it makes sense to make it official. It's probably too late to change the behavior.

**Comment by mnquintana** [comment]
FWIW, we've used it in bundled code too (I'll edit when I find the lines)

It is a rather convenient shorthand, but I don't know if we want to make it official.

**Comment by nathansobo** [comment]
@maxbrunsfeld what do you think here. We just need to decide on something.

* I'd rather be explicit everywhere and always specify the column and fix our packages, but how many packages already copy our antipatterns.
* On the other hand, it's not the end of the world to be slightly less explicit. It's work to change this now that it's out there, so we might as well document it.

**Comment by maxbrunsfeld** [comment]
Yeah, I think that I tried changing this at one point and realized that I couldn't because of existing uses. I'd actually prefer to *not* document this behavior though, and fix any places that are relying on it in core or bundled packages.

**Comment by nathansobo** [comment]
@mnquintana Thanks for bringing this up. If anyone is interested in correcting existing usages to make things more explicit, that would be excellent.

**Pull request closed without merging**
