### PR TITLE
Wait for promises returned by `onWillSave` handlers before saving

### PR DESCRIPTION
**Pull request by maxbrunsfeld**
Refs https://github.com/atom/event-kit/pull/36

### CODE REVIEW

**Comment by szeck87** [comment]
Hi @maxbrunsfeld, does the promise simply need to be returned or does it have to be resolved?  I'm finding that returned rejected promises it's not saving the content of the buffer, though coffeescript isn't my favorite thing and could be a coding issue.  Also looking at the docs here:  https://atom.io/docs/api/v1.21.1/TextBuffer#instance-onWillSave it does say it will not save until the promise is resolved.

**Comment by maxbrunsfeld** [comment]
We will now wait until promises returned from ‘onWillSave’ listeners to resolve before saving the file. If the listeners return a promise that *rejects*, then ‘buffer.save’ will reject with that error, and the file will not be saved.

**Comment by szeck87** [comment]
OK thanks, one more question.  Is it possible to get the file path, or at least the file name and extension, after the save prompt for a file that hasn't been saved yet during onWillSave?  Basically:

1. Create new file
2. Add some content
3. Save it (save prompt appears)
4. Give the file a name/extension and where to save it

That all occurs before any onWillSave code is run, but I can't find any reference to what the user puts in there.

**Comment by maxbrunsfeld** [comment]
Hmm, I don't think you can access that data currently. It would be possible to add it as an argument to the `onWillSave` listener though. Are you interested in submitting a PR to do that?

**Comment by szeck87** [comment]
I could try, I've never looked at this code before nor actually built Atom locally.

**Pull request merged**
