### PR TITLE
Use native MarkerIndex implementation

### PR DESCRIPTION
**Pull request by nathansobo**
Having implemented a simpler binary-tree algorithm for the `MarkerIndex`, I wanted to see what we could gain by [dropping it to C++](https://github.com/atom/marker-index/pull/2). Tests of both implementations vary pretty dramatically between runs, but I'm seeing roughly the following when searching for `e` in jQuery after 6 runs of each version:

| Implementation | Typical Time | Worst Time | Typical Total GC Time
| ------ | ----------- | ---- | ---- |
| native | 900ms | 1070ms | 90ms
| JS | 1200ms | 1500ms | 180ms

So the JS version is definitely more variable, slower overall, and puts more pressure on the garbage collector. A 300-600ms improvement based on my tests. Keep in mind there's a bunch of other stuff going on in this code path, but I wanted to measure a real-world use case for this data structure anyway.

### CODE REVIEW

**Comment by nathansobo** [comment]
@maxbrunsfeld Do you by chance know the incantation I need to give Travis to use clang to build my module instead of gcc?

**Comment by nathansobo** [comment]
Seems like I'm having an issue with the C++11 standard library being available.

**Comment by maxbrunsfeld** [comment]
Currently, in marker-index's `binding.gyp` file, the `-std=c++11` and `-stdlib=libc++` are only set for OSX. We need to set the linux equivalents.

**Comment by nathansobo** [comment]
@maxbrunsfeld Oh of course, we made it conditional. Do you happen to have an example of the Linux equivalents? And Windows? Did you do this for tree-sitter?

**Comment by maxbrunsfeld** [comment]
Maybe just this:

```python
'cflags_cc': [
        '-std=c++0x',
]
```

**Comment by nathansobo** [comment]
Looks like you can just leave the library off. I should set up a marker-index travis build.

**Comment by nathansobo** [comment]
:green_apple:

**Comment by nathansobo** [comment]
Probably should set this up on AppVeyor to make sure we're :cool: on Windows.

**Pull request merged**
